### ISSUE TITLE
java.lang.UnsatisfiedLinkError: unloadOMX_native

### ISSUE THREAD

**Issue by vbauer** [yixia/VitamioBundle#13]
The most popular error in my application (notification error from Google Play Developer's Console):

java.lang.UnsatisfiedLinkError: unloadOMX_native
at io.vov.vitamio.MediaPlayer.unloadOMX_native(Native Method)
at io.vov.vitamio.MediaPlayer.<init>(MediaPlayer.java:135)
at io.vov.vitamio.activity.PlayerService.vplayerInit(PlayerService.java:104)
at io.vov.vitamio.activity.PlayerService.initialize(PlayerService.java:145)
at io.vov.vitamio.activity.VideoActivity$3.handleMessage(VideoActivity.java:566)
at android.os.Handler.dispatchMessage(Handler.java:130)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:4668)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:552)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:917)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
at dalvik.system.NativeStart.main(Native Method)

**Comment by SufianBabri** [comment]
@Ltty by <code>init()</code>, do you mean:

<pre>if(!LibsChecker.checkVitamioLibs(this)) {
    return;
}</pre>

**Comment by SufianBabri** [comment]
I fixed this error by executing `LibsChecker.checkVitamioLibs(this)` every time I opened my player screen.

Somewhere **crossle** said that you have to init Vitamio whenever you update the app version code (i.e if user inited Vitamio in your app **versionCode** 12, he will need to init it again if he updates it to **versionCode** 13, etc. I think it also applies to downgrading).
