### ISSUE TITLE
NPE crash

### ISSUE THREAD

**Issue by infsafe** [yixia/VitamioBundle#139]
java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:278)
    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
    at java.io.File.fixSlashes(File.java:185)
    at java.io.File.(File.java:134)
    at io.vov.vitamio.Vitamio.extractLibs(Unknown Source)
    at io.vov.vitamio.Vitamio.initialize(Unknown Source)
    at io.vov.vitamio.activity.InitActivity$1.doInBackground(Unknown Source)
    at io.vov.vitamio.activity.InitActivity$1.doInBackground(Unknown Source)
    at android.os.AsyncTask$2.call(AsyncTask.java:264)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    ... 5 more
java.lang.NullPointerException
    at java.io.File.fixSlashes(File.java:185)
    at java.io.File.(File.java:134)
    at io.vov.vitamio.Vitamio.extractLibs(Unknown Source)
    at io.vov.vitamio.Vitamio.initialize(Unknown Source)
    at io.vov.vitamio.activity.InitActivity$1.doInBackground(Unknown Source)
    at io.vov.vitamio.activity.InitActivity$1.doInBackground(Unknown Source)
    at android.os.AsyncTask$2.call(AsyncTask.java:264)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)

**Comment by IMEVEN** [comment]
我也看到有这个 log 的上报：
java.lang.NullPointerException
	at java.io.File.fixSlashes(File.java:185)
	at java.io.File.&lt;init&gt;(File.java:134)
	at io.vov.vitamio.Vitamio.extractLibs(Vitamio.java:197)
	at io.vov.vitamio.Vitamio.initialize(Vitamio.java:102)

看代码是

**Comment by IMEVEN** [comment]
我也看到有这个 log 的上报：
java.lang.NullPointerException
at java.io.File.fixSlashes(File.java:185)
at java.io.File.<init>(File.java:134)
at io.vov.vitamio.Vitamio.extractLibs(Vitamio.java:197)
at io.vov.vitamio.Vitamio.initialize(Vitamio.java:102)

看代码是
new File(libPath).delete();
这行报错。

**Comment by MythodeaLoL** [comment]
last version? 4.2.2 @IMEVEN ?
