### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by treworld** [yixia/VitamioBundle#146]
Google Play store crash dump:

java.lang.IllegalStateException
at io.vov.vitamio.MediaPlayer._reset(Native Method)
at io.vov.vitamio.MediaPlayer.reset(MediaPlayer.java:734)
at io.vov.vitamio.widget.VideoView.release(VideoView.java:516)
at io.vov.vitamio.widget.VideoView.access$1500(VideoView.java:67)
at io.vov.vitamio.widget.VideoView$3.surfaceDestroyed(VideoView.java:161)
at android.view.SurfaceView.reportSurfaceDestroyed(SurfaceView.java:617)
at android.view.SurfaceView.updateWindow(SurfaceView.java:502)
at android.view.SurfaceView.updateWindow(SurfaceView.java:408)
at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:217)
at android.view.View.dispatchWindowVisibilityChanged(View.java:4080)
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:720)
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:720)
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:720)
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:720)
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:720)
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:720)
at android.view.ViewRoot.performTraversals(ViewRoot.java:787)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1865)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
at dalvik.system.NativeStart.main(Native Method)

**Comment by bigstark** [comment]
I have a same problem

**Comment by LuckyJayce** [comment]
I have a same problem
