### ISSUE TITLE
dlopen failed: library "nulllibstlport_shared.so"

### ISSUE THREAD

**Issue by sohayb** [yixia/VitamioBundle#236]
Hello, this error is occurring often, the thing is that the library is initialised and I'm able to play a track, once moving to another track, I reset the player before re-initialising it, and the problem occurs there.  
  
    12-25 13:48:11.135  12814-12814/com.sampleapp.sample D/dalvikvm﹕ Trying to load lib /data/app-lib/com.sampleapp.sample-1/libvinit.so 0x41b9dd88
    12-25 13:48:11.135  12814-12814/com.sampleapp.sample D/dalvikvm﹕ Added shared lib /data/app-lib/com.sampleapp.sample-1/libvinit.so 0x41b9dd88
    12-25 13:48:11.135  12814-12814/com.sampleapp.sample D/dalvikvm﹕ Trying to load lib nulllibstlport_shared.so 0x41b9dd88
    12-25 13:48:11.135  12814-12814/com.sampleapp.sample E/dalvikvm﹕ dlopen("nulllibstlport_shared.so") failed: dlopen failed: library "nulllibstlport_shared.so" not found
    12-25 13:48:11.135  12814-12814/com.sampleapp.sample E/Vitamio[Player]﹕ Error loading libs
        java.lang.UnsatisfiedLinkError: dlopen failed: library "nulllibstlport_shared.so" not found
            at java.lang.Runtime.load(Runtime.java:333)
            at java.lang.System.load(System.java:512)
            at io.vov.vitamio.MediaPlayer.<clinit>(MediaPlayer.java:245)
            at com.sampleapp.sample.services.MusicPlayerService.onCreate(MusicPlayerService.java:92)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2589)
            at android.app.ActivityThread.access$1800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5139)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by sohayb** [comment]
The problem is that I was calling `mediaPlayer.getCurrentPosition()` even when the player had nothing to play.

**Comment by AlaeddineOuerteni** [comment]
Hi sohayb
Are you using Service to play Vitamio MediaPlayer ?

**Comment by nightwolf738** [comment]
My error is still happenning like;

java.lang.UnsatisfiedLinkError: dlopen failed: library "nulllibstlport_shared.so" not found
at java.lang.Runtime.load(Runtime.java:331)
at java.lang.System.load(System.java:982)
at io.vov.vitamio.MediaPlayer.<clinit>(MediaPlayer.java:257)

When I call `videoView.setVideoPath(url);`

I am not using any services.

**Comment by sohayb** [comment]
Yes, I'm using a service that hosts the `mediaPlayer` instance.

**Comment by kitek** [comment]
Just call 

```
Vitamio.isInitialized(this);
```

before start video.

**Comment by michaelryannewell** [comment]
Use

System.loadLibrary("stlport_shared");

instead.
