### ISSUE TITLE
Vitamio not supported In over Android API 22.

### ISSUE THREAD

**Issue by StrokeLine** [yixia/VitamioBundle#314]
Dir Conllegue.

I am developing an Android live stream player using your newly distributed library and the Android studio.

By virtue of your well-developed library, I have finished my job very quickly and am satisfied with its performance, especially in case of RTMP and HLS protocol.

However, I found that the player does not work well under Android API 22 environment during compatibility test for various Android versions.

Can I have a solution to cope with the problem?

Since the time given to me is not enough, I want eagerly to get a new library compatible to new released Android phones.

I will wait your prompt reply.

Thanks for your reading.

**Comment by MythodeaLoL** [comment]
Same problem.

```
10-30 02:45:32.525  28429-28853/stream.client D/Vitamio[Player]﹕ loadLibs start 1
10-30 02:45:32.525  28429-28853/stream.client W/ResourceType﹕ No package identifier when getting value for resource number 0x00000000
10-30 02:45:32.525  28429-28853/stream.client E/Vitamio[Player]﹕ loadLib
    android.content.res.Resources$NotFoundException: Resource ID #0x0
            at android.content.res.Resources.getValue(Resources.java:1013)
            at android.content.res.Resources.openRawResource(Resources.java:938)
            at android.content.res.Resources.openRawResource(Resources.java:920)
            at io.vov.vitamio.Vitamio.copyCompressedLib(Vitamio.java:250)
            at io.vov.vitamio.Vitamio.extractLibs(Vitamio.java:205)
            at io.vov.vitamio.Vitamio.initialize(Vitamio.java:104)
            at io.vov.vitamio.activity.InitActivity$1.doInBackground(InitActivity.java:61)
            at io.vov.vitamio.activity.InitActivity$1.doInBackground(InitActivity.java:43)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
```

**Comment by wsw87201326** [comment]
is This project is stop maintenance??

**Comment by FloridaStream** [comment]
"Vitamio for Android (DEPRECATED)" @wsw87201326 =( end of world for me.

**Comment by crossle** [comment]
https://github.com/crossle/VitamioBundle/commit/184c83bfe8ac124e48419869744fa6d834a477da
