### ISSUE TITLE
Xml报错。找不出原因

### ISSUE THREAD

**Issue by ruancaipu** [yixia/VitamioBundle#325]
FATAL EXCEPTION: main
                                                                     Process: io.vov.vitamio.demo, PID: 14509
                                                                     android.view.InflateException: Binary XML file line #13: Error inflating class android.widget.ImageButton
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                         at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
                                                                         at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                         at io.vov.vitamio.widget.MediaController.makeControllerView(MediaController.java:242)
                                                                         at io.vov.vitamio.widget.MediaController.setAnchorView(MediaController.java:225)
                                                                         at io.vov.vitamio.widget.VideoView.attachMediaController(VideoView.java:461)
                                                                         at io.vov.vitamio.widget.VideoView.openVideo(VideoView.java:428)

**Comment by MythodeaLoL** [comment]
Error lines?
