### ISSUE TITLE
Crash when instantiate Vitamio MediaPlayer inside Service

### ISSUE THREAD

**Issue by AlaeddineOuerteni** [yixia/VitamioBundle#333]
dlopen("nulllibstlport_shared.so", RTLD_LAZY) failed: dlopen failed: library "nulllibstlport_shared.so" not found
E/Vitamio[Player]﹕ Error loading libs

java.lang.UnsatisfiedLinkError: dlopen failed: library "nulllibstlport_shared.so" not found
            at java.lang.Runtime.load(Runtime.java:331)
            at java.lang.System.load(System.java:981)
            at io.vov.vitamio.MediaPlayer.<clinit>(MediaPlayer.java:245)

**Comment by MythodeaLoL** [comment]
`nulllibstlport_shared.so` does not exist in vitamio, it did not rename it in sdk vitamio? Causing this error?
<i>Check all files for the library and make sure they are not modified.</i>

**Comment by AlaeddindeOuertani** [comment]
Are you sure that there's no problem with Vitamio inside Service ?

**Comment by AlaeddineOuerteni** [comment]
Please try to play a Vitamio MediaPlayer inside an Android Service

**Comment by AlaeddineOuerteni** [comment]
12-16 17:04:26.301  22125-22125/com.sample.androidapp E/PlayerFragment﹕ Connexion interrompue...
    android.os.DeadObjectException
            at android.os.BinderProxy.transactNative(Native Method)
            at android.os.BinderProxy.transact(Binder.java:511)
            at com.sample.androidapp.service.IRemotePlayerService$Stub$Proxy.startPlayback(IRemotePlayerService.java:535)
            at com.sample.androidapp.fragment.PlayerFragment.startPlayback(PlayerFragment.java:1069)
            at com.sample.androidapp.fragment.PlayerFragment.preroll(PlayerFragment.java:993)
            at com.sample.androidapp.fragment.PlayerFragment.access$1300(PlayerFragment.java:71)
            at com.sample.androidapp.fragment.PlayerFragment$9.onClick(PlayerFragment.java:431)
            at android.view.View.performClick(View.java:5254)
            at android.view.View$PerformClick.run(View.java:21179)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6837)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
12-16 17:04:26.311  22125-22125/com.sample.androidapp E/PlayerFragment﹕ Impossible de contacter le service de lecture...
    android.os.DeadObjectException
            at android.os.BinderProxy.transactNative(Native Method)
            at android.os.BinderProxy.transact(Binder.java:511)
            at com.sample.androidapp.service.IRemotePlayerService$Stub$Proxy.isShowingPreroll(IRemotePlayerService.java:919)
            at com.sample.androidapp.fragment.PlayerFragment.updateView(PlayerFragment.java:652)
            at com.sample.androidapp.fragment.PlayerFragment.update(PlayerFragment.java:631)
            at com.sample.androidapp.fragment.PlayerFragment.access$000(PlayerFragment.java:71)
            at com.sample.androidapp.fragment.PlayerFragment$1.run(PlayerFragment.java:252)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6837)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
12-16 17:04:27.271  23596-23640/com.sample.androidapp:player E/art﹕ dlopen("nulllibstlport_shared.so", RTLD_LAZY) failed: dlopen failed: library "nulllibstlport_shared.so" not found
12-16 17:04:27.271  23596-23640/com.sample.androidapp:player E/Vitamio[Player]﹕ Error loading libs
    java.lang.UnsatisfiedLinkError: dlopen failed: library "nulllibstlport_shared.so" not found
            at java.lang.Runtime.load(Runtime.java:331)
            at java.lang.System.load(System.java:981)
            at io.vov.vitamio.MediaPlayer.<clinit>(MediaPlayer.java:245)
            at com.sample.androidapp.service.PlayerService.getUniqueMediaPlayer(PlayerService.java:156)
            at com.sample.androidapp.service.PlayerService.presetPlayer(PlayerService.java:209)
            at com.sample.androidapp.service.PlayerService.initAndPlay(PlayerService.java:285)
            at com.sample.androidapp.service.PlayerService.access$1200(PlayerService.java:46)
            at com.sample.androidapp.service.PlayerService$4.startPlayback(PlayerService.java:414)
            at com.sample.androidapp.service.IRemotePlayerService$Stub.onTransact(IRemotePlayerService.java:164)
            at android.os.Binder.execTransact(Binder.java:461)
12-16 17:04:27.271  23596-23640/com.sample.androidapp:player E/art﹕ No implementation found for void io.vov.vitamio.MediaPlayer.unloadOMX_native() (tried Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native and Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native__)
12-16 17:04:27.271  23596-23640/com.sample.androidapp:player E/Vitamio[Player]﹕ unloadOMX failed java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.unloadOMX_native() (tried Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native and Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native__)
12-16 17:04:27.271  23596-23640/com.sample.androidapp:player E/art﹕ No implementation found for void io.vov.vitamio.MediaPlayer.native_init() (tried Java_io_vov_vitamio_MediaPlayer_native_1init and Java_io_vov_vitamio_MediaPlayer_native_1init__)
12-16 17:04:27.271  23596-23640/com.sample.androidapp:player E/JavaBinder﹕ **\* Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.native_init() (tried Java_io_vov_vitamio_MediaPlayer_native_1init and Java_io_vov_vitamio_MediaPlayer_native_1init__)
            at io.vov.vitamio.MediaPlayer.native_init(Native Method)
            at io.vov.vitamio.MediaPlayer.<init>(MediaPlayer.java:238)
            at io.vov.vitamio.MediaPlayer.<init>(MediaPlayer.java:192)
            at com.sample.androidapp.service.PlayerService.getUniqueMediaPlayer(PlayerService.java:156)
            at com.sample.androidapp.service.PlayerService.presetPlayer(PlayerService.java:209)
            at com.sample.androidapp.service.PlayerService.initAndPlay(PlayerService.java:285)
            at com.sample.androidapp.service.PlayerService.access$1200(PlayerService.java:46)
            at com.sample.androidapp.service.PlayerService$4.startPlayback(PlayerService.java:414)
            at com.sample.androidapp.service.IRemotePlayerService$Stub.onTransact(IRemotePlayerService.java:164)
            at android.os.Binder.execTransact(Binder.java:461)
12-16 17:04:27.281  23596-23640/com.sample.androidapp:player E/AndroidRuntime﹕ FATAL EXCEPTION: Binder_3
    Process: com.sample.androidapp:player, PID: 23596
    java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.native_init() (tried Java_io_vov_vitamio_MediaPlayer_native_1init and Java_io_vov_vitamio_MediaPlayer_native_1init__)
            at io.vov.vitamio.MediaPlayer.native_init(Native Method)
            at io.vov.vitamio.MediaPlayer.<init>(MediaPlayer.java:238)
            at io.vov.vitamio.MediaPlayer.<init>(MediaPlayer.java:192)
            at com.sample.androidapp.service.PlayerService.getUniqueMediaPlayer(PlayerService.java:156)
            at com.sample.androidapp.service.PlayerService.presetPlayer(PlayerService.java:209)
            at com.sample.androidapp.service.PlayerService.initAndPlay(PlayerService.java:285)
            at com.sample.androidapp.service.PlayerService.access$1200(PlayerService.java:46)
            at com.sample.androidapp.service.PlayerService$4.startPlayback(PlayerService.java:414)
            at com.sample.androidapp.service.IRemotePlayerService$Stub.onTransact(IRemotePlayerService.java:164)
            at android.os.Binder.execTransact(Binder.java:461)

**Comment by AlaeddineOuerteni** [comment]
The problem was solved by removing this line
android:process=":player"
from my service declaration in AndroidManifest.xml
Any explication ?

**Comment by MythodeaLoL** [comment]
https://github.com/yixia/VitamioBundle/issues/236 (Relevant topic)

**Comment by kongsonida** [comment]
just call 
`Vitamio.isInitialized(this);` in onCreated() of MyApplication extend Application

I hope it can help you to fix your problem for VERSION.SDK_INT <= 20

**Comment by xuie0000** [comment]
android:enabled="true"

不要默认启动，通过startService来启动，就不会报错了

**Comment by xuie0000** [comment]
delete 'android:enabled="true"` and use startService

**Comment by xuie0000** [comment]
delete `'android:enabled="true"`， use startService and copy `libarm.so` to you project

抽风的Vitamio，刚才又错了一下？，能不用就不要用吧，用VLC、ijkplayer、MediaPlayer

**Comment by xuie0000** [comment]
再回答一次。

```
+++ b/vitamio/src/io/vov/vitamio/LibsChecker.java
@@ -16,6 +16,7 @@

 package io.vov.vitamio;

+import io.vov.vitamio.activity.InitActivity;
 import android.app.Activity;
 import android.content.Intent;

@@ -37,15 +38,20 @@ public final class LibsChecker {
   public static final String FROM_ME = "fromVitamioInitActivity";

   public static final boolean checkVitamioLibs(Activity ctx) {
+    System.out.println("checkVitamioLibs");
     if (!Vitamio.isInitialized(ctx) && !ctx.getIntent().getBooleanExtra(FROM_ME, false)) {
-      Intent i = new Intent();
-      i.setClassName(Vitamio.getVitamioPackage(), "io.vov.vitamio.activity.InitActivity");
-      i.putExtras(ctx.getIntent());
-      i.setData(ctx.getIntent().getData());
-      i.putExtra("package", ctx.getPackageName());
-      i.putExtra("className", ctx.getClass().getName());
-      ctx.startActivity(i);
-      ctx.finish();
+      System.out.println("checkVitamioLibs false");
+      Vitamio.initialize(ctx, ctx.getResources().getIdentifier("libarm", "raw", ctx.getPackageName()));
```

将

```
if (!LibsChecker.checkVitamioLibs(this)) {
    return;
}
```

放在第一个Acitivty里直接执行完，加载`libarm.so`太费时了，我们早就开始用Vitamio，结果它还在后台加载，这样改直接在主线程加载完，以绝后患
