### ISSUE TITLE
Buffer not large enough for pixels

### ISSUE THREAD

**Issue by Losering** [yixia/VitamioBundle#436]
RuntimeException: Buffer not large enough for pixels

I'd like to get a screenshot of “videoView.getmMediaPlayer().getCurrentFrame()”, but this is a mistake.

**Comment by ooyeah** [comment]
java.lang.RuntimeException: Buffer not large enough for pixels
                                                       at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:547)
                                                       at io.vov.vitamio.MediaPlayer.getCurrentFrame(Native Method)
