### ISSUE TITLE
Audio streaming not working with Vitamio 5.0.2

### ISSUE THREAD

**Issue by Jan31** [yixia/VitamioBundle#446]
After android developer console rejected my APP because I have used Vitamio 4.X library. I trying to use Vitamio 5.0.X version. But after making many changes I am not getting any success. Now I am getting following error

12-22 16:11:41.281 20565-20565/com.example.android.vitamioexample E/art: No implementation found for boolean io.vov.vitamio.MediaPlayer.loadFFmpeg_native(java.lang.String) (tried Java_io_vov_vitamio_MediaPlayer_loadFFmpeg_1native and Java_io_vov_vitamio_MediaPlayer_loadFFmpeg_1native__Ljava_lang_String_2)
12-22 16:11:41.281 20565-20565/com.example.android.vitamioexample E/Vitamio[Player]: Error loading libs
java.lang.UnsatisfiedLinkError: No implementation found for boolean io.vov.vitamio.MediaPlayer.loadFFmpeg_native(java.lang.String) (tried Java_io_vov_vitamio_MediaPlayer_loadFFmpeg_1native and Java_io_vov_vitamio_MediaPlayer_loadFFmpeg_1native__Ljava_lang_String_2)
at io.vov.vitamio.MediaPlayer.loadFFmpeg_native(Native Method)
at io.vov.vitamio.MediaPlayer.loadFFmpeg_native_lib(MediaPlayer.java:253)
at io.vov.vitamio.MediaPlayer.<clinit>(MediaPlayer.java:339)
at io.vov.vitamio.widget.VideoView.openVideo(VideoView.java:427)
at io.vov.vitamio.widget.VideoView.access$1400(VideoView.java:70)
at io.vov.vitamio.widget.VideoView$3.surfaceCreated(VideoView.java:158)
at android.view.SurfaceView.updateWindow(SurfaceView.java:712)
at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:209)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2510)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
at android.view.Choreographer.doCallbacks(Choreographer.java:695)
at android.view.Choreographer.doFrame(Choreographer.java:631)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
12-22 16:11:41.281 20565-20565/com.example.android.vitamioexample E/art: No implementation found for void io.vov.vitamio.MediaPlayer.unloadOMX_native() (tried Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native and Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native__)
12-22 16:11:41.281 20565-20565/com.example.android.vitamioexample E/Vitamio[Player]: unloadOMX failed java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.unloadOMX_native() (tried Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native and Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native__)
12-22 16:11:41.281 20565-20565/com.example.android.vitamioexample E/art: No implementation found for void io.vov.vitamio.MediaPlayer.native_init() (tried Java_io_vov_vitamio_MediaPlayer_native_1init and Java_io_vov_vitamio_MediaPlayer_native_1init__)
12-22 16:11:41.281 20565-20565/com.example.android.vitamioexample D/AndroidRuntime: Shutting down VM
12-22 16:11:41.281 20565-20565/com.example.android.vitamioexample E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.android.vitamioexample, PID: 20565
java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.native_init() (tried Java_io_vov_vitamio_MediaPlayer_native_1init and Java_io_vov_vitamio_MediaPlayer_native_1init__)
at io.vov.vitamio.MediaPlayer.native_init(Native Method)
at io.vov.vitamio.MediaPlayer.<init>(MediaPlayer.java:321)
at io.vov.vitamio.widget.VideoView.openVideo(VideoView.java:427)
at io.vov.vitamio.widget.VideoView.access$1400(VideoView.java:70)
at io.vov.vitamio.widget.VideoView$3.surfaceCreated(VideoView.java:158)
at android.view.SurfaceView.updateWindow(SurfaceView.java:712)
at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:209)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2510)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
at android.view.Choreographer.doCallbacks(Choreographer.java:695)
at android.view.Choreographer.doFrame(Choreographer.java:631)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
12-22 16:11:47.191 20565-20573/com.example.android.vitamioexample E/art: No implementation found for void io.vov.vitamio.MediaPlayer.native_finalize() (tried Java_io_vov_vitamio_MediaPlayer_native_1finalize and Java_io_vov_vitamio_MediaPlayer_native_1finalize__)
12-22 16:11:47.191 20565-20573/com.example.android.vitamioexample E/System: Uncaught exception thrown by finalizer
12-22 16:11:47.191 20565-20573/com.example.android.vitamioexample E/System: java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.native_finalize() (tried Java_io_vov_vitamio_MediaPlayer_native_1finalize and Java_io_vov_vitamio_MediaPlayer_native_1finalize__)
at io.vov.vitamio.MediaPlayer.native_finalize(Native Method)
at io.vov.vitamio.MediaPlayer.finalize(MediaPlayer.java:1062)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:217)
at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
at java.lang.Thread.run(Thread.java:818)
12-22 16:16:41.621 20565-20565/com.example.android.vitamioexample I/Process: Sending signal. PID: 20565 SIG: 9

Please HELP...!

**Comment by ShaoYuzhen** [comment]
Solved?

**Comment by LiycJia** [comment]
Solved?

**Comment by harish141** [comment]
Solved?
