### ISSUE TITLE
Unable to stop activity ava.lang.IndexOutOfBoundsException: Index: 2, Size: 2

### ISSUE THREAD

**Issue by RichardDivid** [yixia/VitamioBundle#494]

**Comment by RichardDivid** [comment]
at android 8.0.0 or 8.0.1,it occur a crash of below:
java.lang.RuntimeException: Unable to stop activity {VideoPlayActivity}: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at android.app.ActivityThread.handleSleeping(ActivityThread.java:4952)
    at android.app.ActivityThread.-wrap23(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at java.util.ArrayList.get(ArrayList.java:437)
    at android.view.WindowManagerGlobal.setStoppedState(WindowManagerGlobal.java:649)
    at android.app.Activity.performStop(Activity.java:7581)
    at android.app.ActivityThread.handleSleeping(ActivityThread.java:4949)
    ... 8 more

**Comment by zr940326** [comment]
我也遇到了，不知道，有解决方案没有

**Comment by zr940326** [comment]
> at android 8.0.0 or 8.0.1,it occur a crash of below:
> java.lang.RuntimeException: Unable to stop activity {VideoPlayActivity}: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
> at android.app.ActivityThread.handleSleeping(ActivityThread.java:4952)
> at android.app.ActivityThread.-wrap23(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
> at android.os.Handler.dispatchMessage(Handler.java:108)
> at android.os.Looper.loop(Looper.java:166)
> at android.app.ActivityThread.main(ActivityThread.java:7529)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
> Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
> at java.util.ArrayList.get(ArrayList.java:437)
> at android.view.WindowManagerGlobal.setStoppedState(WindowManagerGlobal.java:649)
> at android.app.Activity.performStop(Activity.java:7581)
> at android.app.ActivityThread.handleSleeping(ActivityThread.java:4949)
> ... 8 more

兄弟，你最后有解决吗？
