### ISSUE TITLE
NullPointerException (@File:fixSlashes:205) {AsyncTask #2}

### ISSUE THREAD

**Issue by huyduongtu** [yixia/VitamioBundle#88]
This issue doesn't occur frequently. I didn't directly get this issue. But this issue is reported to Play Store a lot.

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:200)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)
Caused by: java.lang.NullPointerException
at java.io.File.fixSlashes(File.java:205)
at java.io.File.init(File.java:189)
at java.io.File.<init>(File.java:139)
at io.vov.vitamio.Vitamio.boolean extractLibs(android.content.Context,int)(SourceFile:169)
at io.vov.vitamio.Vitamio.boolean initialize(android.content.Context)(SourceFile:84)
at io.vov.vitamio.activity.InitActivity$1.java.lang.Object doInBackground(java.lang.Object[])(SourceFile:1)
at android.os.AsyncTask$2.call(AsyncTask.java:185)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
... 4 more

I used version 4.0. Now I uprade to version 4.1. But I'm not sure Whether this issue still occurs or not.
Could you tell help me?
Thanks

**Comment by sbmaggarwal** [comment]
This is happening in Android 5.0 too.
