### ISSUE TITLE
https video streams not working with VitamioBundle v4.0

### ISSUE THREAD

**Issue by fmanzoor** [yixia/VitamioBundle#91]
I tried to integrate the Bundle in my app but failed. Following is the logcat info demanding that ffmpeg be build with SSL support.

To reproduce, find https path of a YouTube video stream and try to play it. Should there be need of any other information for debugging this, please let me know and I will try to help you to the best of my capabilities :-)

```
I/Vitamio[Player]( 4744): isNativeLibsInited, APP VERSION: 1, Vitamio Library version: 1
D/WeTube Debugging ( 4744): playing https://r7---sn-a5m7znes.googlevideo.com/videoplayback?&itag=84&mt=1387806316&id=1afb404c8f51faa0&upn=yu9O_SbLwjs&source=youtube&ms=au&mv=m&expire=1387829937&sver=3&ip=REDACTED&key=yt5&sparams=id,ip,ipbits,itag,ratebypass,source,upn,expire&fexp=941800,919330,932206,939921,916623,901473,909717,932295,936912,936910,923305,936913,907231,907240,921090&ipbits=0&ratebypass=yes&fallback_host=tc.v21.cache5.googlevideo.com&signature=3E6FB5AAADD565707FDABF37491A3DB226F243F8.7E84D66A802AA9D4988FF80DEE1C9BEEFC991022&stereo3d=1&quality=hd720
I/Vitamio[Player]( 4744): LIB ROOT: /data/data/REDACTED/libs/
D/dalvikvm( 4744): Trying to load lib /data/data/REDACTED/libs/libstlport_shared.so 0x40516a90
D/dalvikvm( 4744): Added shared lib /data/data/REDACTED/libs/libstlport_shared.so 0x40516a90
D/dalvikvm( 4744): No JNI_OnLoad found in /data/data/REDACTED/libs/libstlport_shared.so 0x40516a90, skipping init
D/dalvikvm( 4744): Trying to load lib /data/data/REDACTED/libs/libvplayer.so 0x40516a90
D/dalvikvm( 4744): Added shared lib /data/data/REDACTED/libs/libvplayer.so 0x40516a90
I/Vitamio[Player]( 4744): Copyright (c) YIXIA (http://yixia.com).
I/Vitamio[Player]( 4744): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
I/Vitamio[Player]( 4744): LOAD FFMPEG START: /data/data/REDACTED/libs/libffmpeg.so
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSL_shutdown
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSL_free
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSL_CTX_free
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSL_load_error_strings
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSL_library_init
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSL_CTX_new
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSLv23_client_method
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSL_new
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSL_set_fd
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSL_connect
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, SSL_write
E/Vitamio[Player]( 4744): FIND_NAME_SYM ssl, ERR_print_errors_fp
I/Vitamio[Player]( 4744): LOAD FFMPEG END: /data/data/REDACTED/libs/libffmpeg.so
I/Vitamio[Player]( 4744): LOAD VVO START: /data/data/REDACTED/libs/libvvo.9.so
E/Vitamio[Player]( 4744): FIND_NAME_SYM vvo, render_yuv
I/Vitamio[Player]( 4744): LOAD VVO END: /data/data/REDACTED/libs/libvvo.9.so
I/Vitamio[Player]( 4744): LOAD VAO START: /data/data/REDACTED/libs/libvao.0.so
I/Vitamio[Player]( 4744): LOAD VAO END: /data/data/REDACTED/libs/libvao.0.so
I/Vitamio[Player]( 4744): VPLAYER INIT BEGIN
I/Vitamio[Player]( 4744): Copyright (c) YIXIA (http://yixia.com).
I/Vitamio[Player]( 4744): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
I/Vitamio[Player]( 4744): Application package name: REDACTED
D/Vitamio[Player]( 4744): RENDER RGB
D/Vitamio[Player]( 4744): THREAD NOTIFY START
I/Vitamio[Player]( 4744): VPLAYER INIT END
I/Vitamio[Player]( 4744): Copyright (c) YIXIA (http://yixia.com).
I/Vitamio[Player]( 4744): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
I/Vitamio[Player]( 4744): Application package name: REDACTED
E/Vitamio[Player]( 4744): SURFACE INIT FAILED
I/Vitamio[Player]( 4744): Copyright (c) YIXIA (http://yixia.com).
I/Vitamio[Player]( 4744): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
I/Vitamio[Player]( 4744): Application package name: REDACTED
E/Vitamio[Player]( 4744): SURFACE INIT FAILED
D/Vitamio[Player]( 4744): prepare
I/Vitamio[Player]( 4744): PREPARE SIG: 0
I/Vitamio[Player]( 4744): THREAD PREPARE START
I/Vitamio[Player]( 4744): THREAD PREPARE ATTACHED
I/Vitamio[Player]( 4744): Copyright (c) YIXIA (http://yixia.com).
I/Vitamio[Player]( 4744): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
I/Vitamio[Player]( 4744): OPEN FILE https://r7---sn-a5m7znes.googlevideo.com/videoplayback?&itag=84&mt=1387806316&id=1afb404c8f51faa0&upn=yu9O_SbLwjs&source=youtube&ms=au&mv=m&expire=1387829937&sver=3&ip=REDACTED&key=yt5&sparams=id,ip,ipbits,itag,ratebypass,source,upn,expire&fexp=941800,919330,932206,939921,916623,901473,909717,932295,936912,936910,923305,936913,907231,907240,921090&ipbits=0&ratebypass=yes&fallback_host=tc.v21.cache5.googlevideo.com&signature=3E6FB5AAADD565707FDABF37491A3DB226F243F8.7E84D66A802AA9D4988FF80DEE1C9BEEFC991022&stereo3d=1&quality=hd720
D/Vitamio[Player]( 4744): https protocol not found, recompile with openssl or gnutls enabled.
E/Vitamio[Player]( 4744): avformat_open_input: Protocol not found : -1330794744
D/Vitamio[Player]( 4744): CLEAN START
E/Vitamio[Player]( 4744): error (1, -1330794744)
D/WeTube Debugging ( 4744):  trying to play
I/Vitamio[Player]( 4744): FILE CLOSE BEGIN
I/Vitamio[Player]( 4744): FREE VIDEOPIC BEGIN
I/Vitamio[Player]( 4744): FREE VIDEOPIC 2 END
I/Vitamio[Player]( 4744): FREE SUBPIC BEGIN
I/Vitamio[Player]( 4744): FREE SUBPIC 1 END
I/Vitamio[Player]( 4744): FREE AUDIOFRAME BEGIN
I/Vitamio[Player]( 4744): FREE AUDIOFRAME 8 END
I/Vitamio[Player]( 4744): DELETE GLOBAL REF BEGIN
I/Vitamio[Player]( 4744): DELETE GLOBAL REF END
I/Vitamio[Player]( 4744): FILE CLOSE END
D/Vitamio[Player]( 4744): CLEAN END
I/Vitamio[Player]( 4744): THREAD PREPARE DETTACHED
I/Vitamio[Player]( 4744): THREAD PREPARE END
I/ActivityManager(  186): Displayed REDACTED/.Player: +1s657ms
E/Vitamio[Player]( 4744): Error (1, -1330794744)
I/Vitamio[Player]( 4744): VPLAYER INIT BEGIN
I/Vitamio[Player]( 4744): Copyright (c) YIXIA (http://yixia.com).
I/Vitamio[Player]( 4744): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
I/Vitamio[Player]( 4744): Application package name: REDACTED
D/Vitamio[Player]( 4744): RENDER RGB
I/Vitamio[Player]( 4744): VPLAYER INIT END
I/Vitamio[Player]( 4744): Copyright (c) YIXIA (http://yixia.com).
I/Vitamio[Player]( 4744): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
D/Vitamio[Player]( 4744): THREAD NOTIFY START
I/Vitamio[Player]( 4744): Application package name: REDACTED
D/Vitamio[Player]( 4744): SURFACE INIT OK
I/Vitamio[Player]( 4744): Copyright (c) YIXIA (http://yixia.com).
I/Vitamio[Player]( 4744): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
I/Vitamio[Player]( 4744): Application package name: REDACTED
D/Vitamio[Player]( 4744): SURFACE INIT OK
D/Vitamio[Player]( 4744): prepare
I/Vitamio[Player]( 4744): PREPARE SIG: 0
I/Vitamio[Player]( 4744): THREAD PREPARE START
I/Vitamio[Player]( 4744): THREAD PREPARE ATTACHED
I/Vitamio[Player]( 4744): Copyright (c) YIXIA (http://yixia.com).
I/Vitamio[Player]( 4744): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
I/Vitamio[Player]( 4744): OPEN FILE https://r7---sn-a5m7znes.googlevideo.com/videoplayback?&itag=84&mt=1387806316&id=1afb404c8f51faa0&upn=yu9O_SbLwjs&source=youtube&ms=au&mv=m&expire=1387829937&sver=3&ip=REDACTED&key=yt5&sparams=id,ip,ipbits,itag,ratebypass,source,upn,expire&fexp=941800,919330,932206,939921,916623,901473,909717,932295,936912,936910,923305,936913,907231,907240,921090&ipbits=0&ratebypass=yes&fallback_host=tc.v21.cache5.googlevideo.com&signature=3E6FB5AAADD565707FDABF37491A3DB226F243F8.7E84D66A802AA9D4988FF80DEE1C9BEEFC991022&stereo3d=1&quality=hd720
D/Vitamio[Player]( 4744): https protocol not found, recompile with openssl or gnutls enabled.
E/Vitamio[Player]( 4744): avformat_open_input: Protocol not found : -1330794744
D/Vitamio[Player]( 4744): CLEAN START
E/Vitamio[Player]( 4744): error (1, -1330794744)
D/WeTube Debugging ( 4744):  trying to play
I/Vitamio[Player]( 4744): FILE CLOSE BEGIN
I/Vitamio[Player]( 4744): FREE VIDEOPIC BEGIN
I/Vitamio[Player]( 4744): FREE VIDEOPIC 2 END
I/Vitamio[Player]( 4744): FREE SUBPIC BEGIN
I/Vitamio[Player]( 4744): FREE SUBPIC 1 END
I/Vitamio[Player]( 4744): FREE AUDIOFRAME BEGIN
I/Vitamio[Player]( 4744): FREE AUDIOFRAME 8 END
I/Vitamio[Player]( 4744): DELETE GLOBAL REF BEGIN
I/Vitamio[Player]( 4744): DELETE GLOBAL REF END
I/Vitamio[Player]( 4744): FILE CLOSE END
D/Vitamio[Player]( 4744): CLEAN END
I/Vitamio[Player]( 4744): THREAD PREPARE DETTACHED
I/Vitamio[Player]( 4744): THREAD PREPARE END
E/Vitamio[Player]( 4744): Error (1, -1330794744)
```

-Fahad

PS Following is the AndroidManifest.xml of the bundle which I am using.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="io.vov.vitamio"
          android:versionCode="400"
          android:versionName="4.0">

    <uses-sdk
            android:minSdkVersion="7"
            android:targetSdkVersion="17"/>

    <application
            android:icon="@drawable/ic_launcher"
            android:label="Vitamio">
        <activity
                android:name="io.vov.vitamio.activity.InitActivity"
                android:configChanges="orientation|screenSize|smallestScreenSize|keyboard|keyboardHidden|navigation"
                android:launchMode="singleTop"
                android:theme="@android:style/Theme.NoTitleBar"
                android:windowSoftInputMode="stateAlwaysHidden"/>
    </application>
</manifest>
```

**Comment by jemshit** [comment]
I get error on LG G4:

```
03-01 17:13:00.791: E/Vitamio[Player](24079): Error loading libs
03-01 17:13:00.791: E/Vitamio[Player](24079): java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/data/my.example.com/lib/libstlport_shared.so" not found
03-01 17:13:00.791: E/Vitamio[Player](24079):   at java.lang.Runtime.load(Runtime.java:331)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at java.lang.System.load(System.java:981)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at io.vov.vitamio.MediaPlayer.<clinit>(SourceFile:257)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at io.vov.vitamio.widget.VideoView.openVideo(SourceFile:431)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at io.vov.vitamio.widget.VideoView.access$1400(SourceFile:70)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at io.vov.vitamio.widget.VideoView$3.surfaceCreated(SourceFile:162)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.view.SurfaceView.updateWindow(SurfaceView.java:593)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2004)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1085)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5984)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.view.Choreographer.doCallbacks(Choreographer.java:580)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.view.Choreographer.doFrame(Choreographer.java:550)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.os.Handler.handleCallback(Handler.java:739)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.os.Handler.dispatchMessage(Handler.java:95)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.os.Looper.loop(Looper.java:135)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at android.app.ActivityThread.main(ActivityThread.java:5425)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at java.lang.reflect.Method.invoke(Native Method)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at java.lang.reflect.Method.invoke(Method.java:372)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
03-01 17:13:00.791: E/Vitamio[Player](24079):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
03-01 17:13:00.791: E/art(24079): No implementation found for void io.vov.vitamio.MediaPlayer.unloadOMX_native() (tried Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native and Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native__)
03-01 17:13:00.791: E/Vitamio[Player](24079): unloadOMX failed java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.unloadOMX_native() (tried Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native and Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native__)
03-01 17:13:00.791: E/art(24079): No implementation found for void io.vov.vitamio.MediaPlayer.native_init() (tried Java_io_vov_vitamio_MediaPlayer_native_1init and Java_io_vov_vitamio_MediaPlayer_native_1init__)
03-01 17:13:00.791: E/AndroidRuntime(24079): FATAL EXCEPTION: main
03-01 17:13:00.791: E/AndroidRuntime(24079): Process: my.example.com, PID: 24079
03-01 17:13:00.791: E/AndroidRuntime(24079): java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.native_init() (tried Java_io_vov_vitamio_MediaPlayer_native_1init and Java_io_vov_vitamio_MediaPlayer_native_1init__)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at io.vov.vitamio.MediaPlayer.native_init(Native Method)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at io.vov.vitamio.MediaPlayer.<init>(SourceFile:249)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at io.vov.vitamio.widget.VideoView.openVideo(SourceFile:431)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at io.vov.vitamio.widget.VideoView.access$1400(SourceFile:70)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at io.vov.vitamio.widget.VideoView$3.surfaceCreated(SourceFile:162)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.view.SurfaceView.updateWindow(SurfaceView.java:593)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2004)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1085)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5984)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.view.Choreographer.doFrame(Choreographer.java:550)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.os.Handler.handleCallback(Handler.java:739)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.os.Handler.dispatchMessage(Handler.java:95)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.os.Looper.loop(Looper.java:135)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at android.app.ActivityThread.main(ActivityThread.java:5425)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at java.lang.reflect.Method.invoke(Native Method)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at java.lang.reflect.Method.invoke(Method.java:372)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
03-01 17:13:00.791: E/AndroidRuntime(24079):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
03-01 17:13:09.471: E/[IFTTT]LGIFTTTWidgetProvider(4032): [LGIFTTTWidgetProvider.java:98:onReceive()]onReceive intent =android.appwidget.action.APPWIDGET_UPDATE
03-01 17:13:17.251: E/ThermalEngine(480): [GPU_MON] ACTION: GPU - [GPU_MON] Setting GPU[0] to 600000000
```

**Comment by MythodeaLoL** [comment]
@jemshit don't change /io/vov/vitamio files, replace libarm.so with last libarm updated.

Vitamio working good, this problem is in your custom integration.

<i>Your information is limited for a debug.</i>
Please, in the next, search or <b>open a new issue</b>. 

<h1>Avoid post here, please.</h1>
